#!/usr/bin/env python3
"""
Generate font_chinese_data.h — a sorted Unicode→HZK16 offset lookup table.

Usage:
    python generate_font_data.py [output_path]

If output_path is omitted, writes to:
    ../main/display/font_chinese_data.h

HZK16 file layout:
    The HZK16 font binary contains 16×16 bitmaps for GB2312 characters,
    ordered by GB2312 internal code (qu-wei ma).  Each character is
    32 bytes (16 rows × 2 bytes per row, MSB left).

    GB2312 code range:    0xA1A1 – 0xF7FE
    Zones used:           1–9, 16–87  (zones 10–15, 88–94 are empty/reserved)
    HZK16 offset formula: ((qu - 0xA1) * 94 + (wei - 0xA1)) * 32

Output header format:
    const uint16_t unicode_to_hzk[][2] = {
        {unicode_codepoint, hzk16_offset_32_units},
        ...
    };
"""

import os
import sys


def gb2312_to_unicode(qu, wei):
    """Convert GB2312 qu-wei code to Unicode codepoint using Python's codec."""
    try:
        gb_bytes = bytes([qu, wei])
        text = gb_bytes.decode('gb2312')
        if len(text) == 1:
            return ord(text)
    except (UnicodeDecodeError, LookupError):
        pass
    return None


def is_valid_gb2312_zone(qu):
    """Return True if this zone is used in GB2312."""
    return (1 <= qu <= 9) or (16 <= qu <= 87)


def generate_table():
    """Generate sorted {unicode_codepoint, hzk16_offset} pairs."""
    entries = []

    for qu in range(0xA1, 0xF8):   # 0xA1–0xF7
        zone = qu - 0xA0
        if not is_valid_gb2312_zone(zone):
            continue

        for wei in range(0xA1, 0xFF):  # 0xA1–0xFE
            cp = gb2312_to_unicode(qu, wei)
            if cp is None:
                continue

            # HZK16 offset in units of 32 bytes
            # offset = ((qu - 0xA1) * 94 + (wei - 0xA1))
            offset = (qu - 0xA1) * 94 + (wei - 0xA1)

            entries.append((cp, offset))

    # Sort by Unicode codepoint ascending
    entries.sort(key=lambda x: x[0])

    return entries


def write_header(entries, path):
    """Write the C header file with the sorted mapping table."""
    with open(path, 'w', encoding='utf-8') as f:
        f.write("""/**
 * @file font_chinese_data.h
 * @brief Auto-generated Unicode → HZK16 offset lookup table.
 *
 * DO NOT EDIT MANUALLY — generated by scripts/generate_font_data.py
 *
 * Format: sorted array of {uint16_t unicode, uint16_t hzk16_offset_32}
 *   hzk16_offset_32 = byte offset into HZK16 binary divided by 32.
 *   Actual file offset = hzk16_offset_32 * 32.
 *
 * Usage: binary-search unicode_to_hzk for the codepoint; read 32 bytes
 *        from HZK16 at `hzk16_offset_32 * 32` to get the 16×16 bitmap.
 */

#pragma once

#include <stdint.h>

/* Number of entries in the mapping table */
#define UNICODE_TO_HZK_COUNT  %d

/* {unicode_codepoint, hzk16_offset_in_32byte_units} — sorted by unicode */
static const uint16_t unicode_to_hzk[UNICODE_TO_HZK_COUNT][2] = {
""" % len(entries))

        for i, (cp, offset) in enumerate(entries):
            # Print 4 entries per line
            if i % 4 == 0:
                f.write("    ")
            f.write("{%5d,%5d}" % (cp, offset))
            if i < len(entries) - 1:
                f.write(", ")
            if i % 4 == 3:
                f.write("\n")
        if len(entries) % 4 != 0:
            f.write("\n")

        f.write("""};

/**
 * @brief Binary-search the mapping table for a Unicode codepoint.
 *
 * @param cp  Unicode codepoint to search for
 * @param out_offset  if found, receives the HZK16 offset (32-byte units)
 * @return true if found, false otherwise
 */
static inline bool hzk_lookup(uint32_t cp, uint16_t *out_offset)
{
    int lo = 0, hi = UNICODE_TO_HZK_COUNT - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        uint16_t mid_cp = unicode_to_hzk[mid][0];
        if (mid_cp == (uint16_t)cp) {
            *out_offset = unicode_to_hzk[mid][1];
            return true;
        } else if (mid_cp < (uint16_t)cp) {
            lo = mid + 1;
        } else {
            hi = mid - 1;
        }
    }
    return false;
}
""")

    print(f"Generated {path} with {len(entries)} entries")


def main():
    # Determine output path
    script_dir = os.path.dirname(os.path.abspath(__file__))
    default_output = os.path.join(script_dir, '..', 'main', 'display',
                                  'font_chinese_data.h')
    output_path = sys.argv[1] if len(sys.argv) > 1 else default_output
    output_path = os.path.normpath(output_path)

    entries = generate_table()
    print(f'Found {len(entries)} GB2312 → Unicode mappings')

    if len(entries) == 0:
        print('ERROR: No mappings found! Is the gb2312 codec available?')
        sys.exit(1)

    write_header(entries, output_path)


if __name__ == '__main__':
    main()
